INSERT INTO EMPLOYEE(EMPLOYEE_NAME,YEARS_OF_EXPERIENCE) VALUES('PRIYANKA',2);
INSERT INTO EMPLOYEE(EMPLOYEE_NAME,YEARS_OF_EXPERIENCE) VALUES('Srabani',5);
INSERT INTO EMPLOYEE(EMPLOYEE_NAME,YEARS_OF_EXPERIENCE) VALUES('Sudip',12);
INSERT INTO EMPLOYEE(EMPLOYEE_NAME,YEARS_OF_EXPERIENCE) VALUES('Megha',7);
INSERT INTO EMPLOYEE(EMPLOYEE_NAME,YEARS_OF_EXPERIENCE) VALUES('Ritesh',5);
INSERT INTO EMPLOYEE(EMPLOYEE_NAME,YEARS_OF_EXPERIENCE) VALUES('Ashish',3);
